version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: workout-app-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00tr00t
      MYSQL_DATABASE: workout_app
      MYSQL_USER: myuser
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
