services:
  mysql:
    image: mysql:8.0
    container_name: workout-app-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00tr00t
      MYSQL_DATABASE: workout_app
      MYSQL_USER: myuser
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: workout-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: production
      DB_HOST: root
      DB_USER: r00tr00t
      DB_PASS: userpassword
      DB_NAME: workout_app
    stdin_open: true
    tty: true
    command: npm run start:prod

volumes:
  mysql_data:
